### ISSUE TITLE
Remove Directory Option

### ISSUE THREAD

**Issue by una** [una/sass-director#12]
Remove the option for a directory since this should ALWAYS be inside of the same directory as main.scss (the files are all relative to it)

**Comment by una** [comment]
@jonathantneal  what do you think of this -- what is the benefit of the directory option?

**Comment by jonathantneal** [comment]
I would default to the opinionated guidelines and keep the option. I would be heavily influenced by whether or not changing base directories is part of sass or libsass.

**Comment by una** [comment]
But what I'm saying is, if i do `sass-director main.scss sass`

The files are out of sync. main.scss does not change, but the files have been creates in the `sass/` directory. main.scss is now inaccurate -- pointing to nonexistant files.

You get a main.scss:
```
@import 'base/h1';
```

But the files created are:
```
sass/base/h1
```

It is out of sync. The only time it would make sense is ```sass-director sass/main.scss sass` but you shouldn't need the second argument anyway.

See what I'm saying?

**Comment by una** [comment]
Made you a collaborator, @jonathantneal

**Comment by una** [comment]
fixed in PR 19
