### ISSUE TITLE
Atom Editor Package

### ISSUE THREAD

**Issue by sturobson** [una/sass-director#18]
As I tweeted: https://twitter.com/StuRobson/status/558723718072238081

It'd be great if someone who knows how to, to make an Atom package for this. I have looked into atom packages but

![mind explodes](http://www.reactiongifs.com/r/2013/10/tim-and-eric-mind-blown.gif "Mind explodes")

**Comment by Stephn-R** [comment]
Hey, take a look here: https://github.com/Sass-Director/Sass-Director_Atom
