### ISSUE TITLE
Create CLI 

### ISSUE THREAD

**Issue by una** [una/sass-director#3]
create node cli to enable `sass-director file-name.scss` to build out the files

**Comment by una** [comment]
It would also be nice to do this from anywhere in the project:  (sass-director <manifest-file> <base-directory>) i.e.

`sass-director sass/main.scss sass/`

So a user could do all of this in the cli: mkdir sass; cd sass; touch main.scss; vim main.scss; --type out architecture--; :wq, `sass-director main.scss` (if there's no third argument for the folder, it will be the current path)

**Comment by jonathantneal** [comment]
I love this project, and I was thinking the same thing. I would love to help with this!

**Comment by una** [comment]
Sure! If you want to submit a PR I'd be happy to take a look :)

**Comment by jonathantneal** [comment]
Great, I’ll do that shortly!

**Comment by jonathantneal** [comment]
I’ll start work on a Node version, too. Folks might prefer that.

**Comment by una** [comment]
Yep :) A node cli is what I originally had in mind because of how easy it is to globally npm install

**Comment by jonathantneal** [comment]
Okay, I’ve also submitted an initial Node version.
